.PHONY: help
help: ## Show this help.
	@echo "run-unit-test 		start all unit tests"
	@echo "clean 			clean all tmp files"

.PHONY: run-unit-test
run-unit-test:
	python ./test_unit.py

.PHONY: run-func-test
run-func-test:
	python ./test_unit.py

.PHONY: run-linter
run-linter:
	exit 0

.PHONY: clean
clean:
	exit 0